### ISSUE TITLE
chkservice exits on terminal resize

### ISSUE THREAD

**Issue by bl33pbl0p** [linuxenko/chkservice#5]
* Bug

When running chkservice, and maximizing/resizing the terminal window, the application quits. No error codes are emitted either.

* Steps to reproduce

1. Run chkservice
2. Resize the terminal window it is running in.

**Comment by linuxenko** [comment]
you know, it's standard behaviour for terminal window resizing. i dont like bother user with restarting the application on sigwinch as another apps do.

**Comment by bl33pbl0p** [comment]
I find that a bit odd, most ncurses applications do not do that. The user actually would be more bothered if you don't fix this, imo. Think of it, invoking it in a floating window, and then wanting to maximize the window, only realizing that it quits as soon as the terminal resizes.

**Comment by linuxenko** [comment]
I've read in the `ncurses` docs [about](https://github.com/linuxenko/chkservice/blob/master/src/chk-wmain.cpp#L41) such cases said it is good to exit on `sigwinch` because terminals does not handle resizing or something like this. Please make a PR of your idea, i'm sure it would be cool to handle such case without restarts.

**Comment by bl33pbl0p** [comment]
I don't do C++ really, but calling MainWindow(); again from the signal handler does not make it quit, though it won't correctly resize, I think you can just reinitialize the program when the terminal is changed, and I will need your help in that if it is okay to do.
